### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 215: ordinal not in range(128)

### ISSUE THREAD

**Issue by WoRiX** [gobytecoin/sentinel#2]
The sentinel was falling to start properly because I use an invalid character. The faulty one was : 'é' and used in the RPC password in the gobyte.conf file.

Here's the trace log I had access to :

SENTINEL_DEBUG=1 ./venv/bin/python bin/sentinel.py

2019-01-27 06:07:57 [info]: SCHEMA_VERSION (code) = [20170111-1]
2019-01-27 06:07:57 [info]: DB_SCHEMA_VERSION = [20170111-1]
Traceback (most recent call last):
  File "bin/sentinel.py", line 265, in <module>
    main()
  File "bin/sentinel.py", line 164, in main
    if not is_gobyted_port_open(gobyted):
  File "bin/sentinel.py", line 151, in is_gobyted_port_open
    info = gobyted.rpc_command('getgovernanceinfo')
  File "lib/gobyted.py", line 42, in rpc_command
    return self.rpc_connection.__getattr__(params[0])(*params[1:])
  File "lib/gobyted.py", line 31, in rpc_connection
    return AuthServiceProxy("http://{0}:{1}@{2}:{3}".format(*self.creds))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 215: ordinal not in range(128)

**Comment by marknl** [comment]
Correct. You shouldn't use special characters in passwords. This is currently a limitation of the sentinel code.

**Comment by WoRiX** [comment]
Alright thanks for answer !

I just wanted to point it out.

No big deal about it ;-)
